// <auto-generated />
using System;
using WorkScout.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WorkScout.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("WorkScout.Models.AppSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppPasswordEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDemoMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("WorkScout.Models.InboundMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyPreview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("JobApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalMessageId")
                        .IsUnique();

                    b.HasIndex("JobApplicationId");

                    b.ToTable("InboundMessages");
                });

            modelBuilder.Entity("WorkScout.Models.JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CvPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobListingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobListingId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("WorkScout.Models.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFound")
                        .HasColumnType("TEXT");

                    b.Property<string>("Portal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("JobListings");
                });

            modelBuilder.Entity("WorkScout.Models.Portal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Portals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsSelected = true,
                            Name = "Jobs.cz"
                        },
                        new
                        {
                            Id = 2,
                            IsSelected = true,
                            Name = "Prace.cz"
                        },
                        new
                        {
                            Id = 3,
                            IsSelected = true,
                            Name = "StartupJobs"
                        },
                        new
                        {
                            Id = 4,
                            IsSelected = false,
                            Name = "LinkedIn"
                        });
                });

            modelBuilder.Entity("WorkScout.Models.InboundMessage", b =>
                {
                    b.HasOne("WorkScout.Models.JobApplication", "JobApplication")
                        .WithMany("InboundMessages")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("WorkScout.Models.JobApplication", b =>
                {
                    b.HasOne("WorkScout.Models.JobListing", "JobListing")
                        .WithMany()
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobListing");
                });

            modelBuilder.Entity("WorkScout.Models.JobApplication", b =>
                {
                    b.Navigation("InboundMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
